package com.fetchclone

import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.List
import androidx.compose.material.icons.filled.ShoppingCart
import androidx.compose.material3.Icon
import androidx.compose.material3.NavigationBar
import androidx.compose.material3.NavigationBarItem
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.navigation.NavDestination
import androidx.navigation.NavDestination.Companion.hierarchy
import androidx.navigation.NavGraph.Companion.findStartDestination
import androidx.navigation.NavHostController
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.currentBackStackEntryAsState
import androidx.navigation.compose.rememberNavController
import com.fetchclone.feature.offers.OffersRoutes
import com.fetchclone.feature.offers.navigateToOfferDetail
import com.fetchclone.feature.offers.offerDetailScreen
import com.fetchclone.feature.offers.offersFeedScreen
import com.fetchclone.feature.receipts.ReceiptsRoutes
import com.fetchclone.feature.receipts.receiptsScreen

/**
 * App root: owns the single [NavHost] and the bottom navigation bar.
 *
 * Each feature module contributes its own `NavGraphBuilder` extensions
 * ([offersFeedScreen], [offerDetailScreen], [receiptsScreen]); this file only assembles
 * them and supplies cross-feature callbacks. Adding a feature stays a couple of lines here.
 */
@Composable
fun FetchCloneApp() {
    val navController = rememberNavController()
    val currentDestination = navController.currentDestination()

    Scaffold(
        bottomBar = {
            // Hidden on non-top-level destinations, so pushing the offer detail screen
            // gives it the full window. Deriving visibility from the current destination
            // rather than tracking a boolean means it can never disagree with the back
            // stack — including after a process-death restore, which a remembered flag
            // would get wrong.
            if (currentDestination.isTopLevel()) {
                FetchCloneBottomBar(navController, currentDestination)
            }
        },
    ) { contentPadding ->
        NavHost(
            navController = navController,
            startDestination = OffersRoutes.FEED,
            // Only the BOTTOM inset is consumed here. Each screen has its own `Scaffold`
            // with its own top app bar, and those already apply the status-bar inset —
            // passing the full `contentPadding` down would apply it twice and leave a
            // visible gap under every top bar. The bottom bar is this file's to own, so
            // its height is this file's to reserve.
            modifier = Modifier.padding(bottom = contentPadding.calculateBottomPadding()),
        ) {
            offersFeedScreen(onOfferClick = navController::navigateToOfferDetail)
            offerDetailScreen(onBack = navController::navigateUp)
            receiptsScreen()
        }
    }
}

@Composable
private fun FetchCloneBottomBar(
    navController: NavHostController,
    currentDestination: NavDestination?,
) {
    NavigationBar {
        TopLevelDestination.entries.forEach { destination ->
            NavigationBarItem(
                // `hierarchy` rather than `route ==`: it walks the destination's parent
                // graphs, so a tab stays selected for nested destinations within it. It is
                // the right comparison even though this graph is currently flat — writing
                // the equality version means the highlight silently breaks the first time
                // someone nests a screen.
                selected = currentDestination.isIn(destination),
                onClick = { navController.navigateToTopLevel(destination) },
                icon = { Icon(destination.icon, contentDescription = null) },
                label = { Text(destination.label) },
            )
        }
    }
}

/**
 * The bottom bar's tabs.
 *
 * An enum, so the bar is generated by iterating rather than hand-written per tab — adding
 * a third feature is one entry, not a copy-pasted `NavigationBarItem`. Each entry
 * references the route constant its own feature module exports, so `:app` never
 * hardcodes a route string.
 */
private enum class TopLevelDestination(
    val route: String,
    val label: String,
    val icon: ImageVector,
) {
    Offers(OffersRoutes.FEED, "Offers", Icons.Filled.ShoppingCart),
    Receipts(ReceiptsRoutes.LIST, "Receipts", Icons.Filled.List),
}

@Composable
private fun NavHostController.currentDestination(): NavDestination? {
    val backStackEntry by currentBackStackEntryAsState()
    return backStackEntry?.destination
}

private fun NavDestination?.isTopLevel(): Boolean =
    TopLevelDestination.entries.any { this.isIn(it) }

private fun NavDestination?.isIn(destination: TopLevelDestination): Boolean =
    this?.hierarchy?.any { it.route == destination.route } == true

/**
 * Switches tabs the way a bottom bar is supposed to.
 *
 * The three options are the canonical combination, and each fixes a specific bug you get
 * without it:
 *
 * - **`popUpTo(startDestination) { saveState = true }`** — without it, every tab tap pushes
 *   onto the back stack, so a user who tapped between tabs five times has to press Back
 *   five times to leave the app. `saveState` preserves each tab's scroll position and
 *   ViewModel state as it is popped.
 * - **`launchSingleTop`** — without it, re-tapping the tab you are already on pushes a
 *   duplicate copy of the same screen.
 * - **`restoreState`** — the counterpart to `saveState`. Without it the state is saved and
 *   then never read, so returning to a tab resets it to the top.
 *
 * `saveState`/`restoreState` are why the offers feed does not re-fetch and re-scroll every
 * time the user checks their receipts.
 */
private fun NavHostController.navigateToTopLevel(destination: TopLevelDestination) {
    navigate(destination.route) {
        popUpTo(graph.findStartDestination().id) { saveState = true }
        launchSingleTop = true
        restoreState = true
    }
}
